# Generated by Django 2.2.1 on 2019-05-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LearningAPI', '0002_cohorttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisengagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thec_code', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LearningAPI.Instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDisengagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disengagement_detail', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField(blank=True)),
                ('last_attendance_date', models.DateField(blank=True)),
                ('intended_return_date', models.DateField(blank=True, null=True)),
                ('return_conditions', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('pdf_slug', models.CharField(blank=True, max_length=120, null=True)),
                ('cohort_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LearningAPI.CohortType')),
                ('disengagement_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_disengagement.DisengagementType')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LearningAPI.Instructor')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_disengagement.ReasonCode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.Student')),
            ],
            options={
                'unique_together': {('student', 'effective_date')},
            },
        ),
    ]
