# Generated by Django 2.2.1 on 2019-05-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_disengagement', '0002_studentnote_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdisengagement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disengaged_student', to='LearningAPI.Student'),
        ),
    ]
