# Generated by Django 2.2.1 on 2019-05-08 23:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slack_channel', models.CharField(blank=True, max_length=55)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_awesome', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='LeadGenerationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='NssUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_handle', models.CharField(max_length=55)),
                ('github_handle', models.CharField(max_length=55)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='\\(?\\d+\\)?[-.\\s]?\\d+[-.\\s]?\\d+')])),
                ('student_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='TreehouseBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('technology', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('capstone_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.CapstoneType')),
                ('nss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
                ('proposal_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.ProposalStatus')),
            ],
        ),
        migrations.CreateModel(
            name='PreworkPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javascript', models.IntegerField()),
                ('css', models.IntegerField()),
                ('html', models.IntegerField()),
                ('python', models.IntegerField()),
                ('ruby', models.IntegerField()),
                ('node', models.IntegerField()),
                ('csharp', models.IntegerField()),
                ('other', models.IntegerField()),
                ('nss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Company')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.JobType')),
                ('nss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
                ('technologies', models.ManyToManyField(to='LearningAPI.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='NssUserExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Exercise')),
                ('nss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
            ],
        ),
        migrations.CreateModel(
            name='NssUserCohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Cohort')),
                ('nss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
            ],
        ),
        migrations.CreateModel(
            name='NssUserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
                ('treehouse_badge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.TreehouseBadge')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Cohort')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(to='LearningAPI.Contact'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='instructors',
            field=models.ManyToManyField(through='LearningAPI.InstructorCohort', to='LearningAPI.Instructor'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='students',
            field=models.ManyToManyField(through='LearningAPI.StudentCohort', to='LearningAPI.Student'),
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=55)),
                ('application_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.ApplicationStageType')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Contact')),
                ('lead_generation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.LeadGenerationType')),
                ('nss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
            ],
        ),
    ]
