# Generated by Django 2.0.6 on 2018-06-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0002_leadstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadstatus',
            old_name='nss_user_id',
            new_name='nss_user',
        ),
    ]
