# Generated by Django 2.2.1 on 2019-05-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0002_cohorttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_number']},
        ),
    ]
