# Generated by Django 2.2.1 on 2019-12-12 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0004_auto_20190514_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcohort',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='students',
            field=models.ManyToManyField(related_name='instr_student', through='LearningAPI.InstructorStudent', to='LearningAPI.Student'),
        ),
    ]
