# Generated by Django 2.0.6 on 2018-06-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0004_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=55)),
                ('notes', models.TextField()),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Company')),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Contact')),
            ],
        ),
    ]
