# Generated by Django 2.0.6 on 2018-06-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0005_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Company'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Contact'),
        ),
    ]
