# Generated by Django 2.2.1 on 2019-12-12 02:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0005_auto_20191212_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcohort',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='instructorcohort',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cohorts', to='LearningAPI.Instructor'),
        ),
        migrations.AlterField(
            model_name='studentcohort',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cohorts', to='LearningAPI.Student'),
        ),
    ]
