# Generated by Django 2.0.6 on 2018-06-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0006_leadgenerationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_generation_type_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.LeadGenerationType'),
        ),
    ]
