# Generated by Django 2.0.6 on 2018-06-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0006_auto_20180606_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
