# Generated by Django 2.0.6 on 2018-06-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0007_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=55)),
                ('start_date', models.DateField(max_length=55)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Company')),
                ('job_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.JobType')),
                ('nss_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
            ],
        ),
    ]
