# Generated by Django 2.0.6 on 2018-06-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0008_placement'),
        ('LearningAPI', '0006_applicationstagetype'),
    ]

    operations = [
    ]
