# Generated by Django 2.0.6 on 2018-06-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0009_company_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contacts',
        ),
    ]
