# Generated by Django 2.0.6 on 2018-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0009_merge_20180618_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(to='LearningAPI.Contact'),
        ),
        migrations.AddField(
            model_name='placement',
            name='technologies',
            field=models.ManyToManyField(to='LearningAPI.Technology'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
