# Generated by Django 2.0.6 on 2018-06-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0009_companycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Placement')),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Technology')),
            ],
        ),
    ]
