# Generated by Django 2.0.6 on 2018-06-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0010_auto_20180620_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=55)),
                ('application_stage_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.ApplicationStageType')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Company')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.Contact')),
                ('lead_generation_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.LeadGenerationType')),
                ('nss_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.NssUser')),
            ],
        ),
        migrations.AlterField(
            model_name='placement',
            name='start_date',
            field=models.DateField(),
        ),
    ]
