# Generated by Django 2.0.6 on 2018-06-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0010_placementtechnology'),
        ('LearningAPI', '0006_applicationstagetype'),
    ]

    operations = [
    ]
