# Generated by Django 2.0.6 on 2018-06-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0011_merge_20180618_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='companies',
            field=models.ManyToManyField(to='LearningAPI.Company'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='CompanyContact',
        ),
    ]
