# Generated by Django 2.0.6 on 2018-06-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0011_auto_20180620_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationstage',
            old_name='application_stage_type_id',
            new_name='application_stage_type',
        ),
        migrations.RenameField(
            model_name='applicationstage',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='applicationstage',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='applicationstage',
            old_name='lead_generation_type_id',
            new_name='lead_generation_type',
        ),
        migrations.RenameField(
            model_name='applicationstage',
            old_name='nss_user_id',
            new_name='nss_user',
        ),
    ]
