# Generated by Django 2.0.6 on 2018-06-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0012_auto_20180618_1940'),
        ('LearningAPI', '0009_merge_20180618_1944'),
    ]

    operations = [
    ]
