# Generated by Django 2.0.6 on 2018-06-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0013_merge_20180618_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementtechnology',
            name='placement_id',
        ),
        migrations.RemoveField(
            model_name='placementtechnology',
            name='technology_id',
        ),
        migrations.AddField(
            model_name='placement',
            name='technologies',
            field=models.ManyToManyField(to='LearningAPI.Technology'),
        ),
        migrations.DeleteModel(
            name='PlacementTechnology',
        ),
    ]
